hamrokurakani/chat/routes.py
from datetime import datetime

from flask import Blueprint, abort, redirect, render_template, session, url_for
from flask_login import current_user, login_required
from flask_socketio import emit, join_room, leave_room
from hamrokurakani import db, socketio
from hamrokurakani.core.des import DesKey
from hamrokurakani.models import Message, User

chyat = Blueprint('chat', __name__, template_folder='templates')


@chyat.route('/chats')
@login_required
def home():
    users = User.query.all()
    total_users = len(list(users))
    return render_template('chat/users.html', users=users, total_users=total_users)


@chyat.route('/chatwith/<string:user>')
@login_required
def chatwith(user):
    getuser = User.query.filter_by(username=user).first_or_404()
    messages = []
    session['receiver_id'] = getuser.id
    session['room'] = int(getuser.id) * int(current_user.id)
    msgs_received = list(Message.query.filter_by(
        recipient_id=current_user.id, sender_id=getuser.id).all())
    msgs_sent = list(Message.query.filter_by(
        recipient_id=getuser.id, sender_id=current_user.id).all())
    messages = msgs_received + msgs_sent
    messages.sort(key=lambda order_by: order_by.timestamp)
    current_user.last_message_read_time = datetime.now()
    for message in msgs_received:
        message.is_seen = True
    db.session.commit()
    return render_template('chat/chatter.html', getuser=getuser, users=User.query.all(), messages=messages)


@chyat.route("/chatwith/<string:user>/deletemessage/<int:id>/")
@login_required
def deletemessage(user, id):
    message = Message.query.filter_by(id=id).first_or_404()
    if not current_user.is_authenticated and message.author != current_user:
        abort(403)
    db.session.delete(message)
    db.session.commit()
    return redirect(url_for('chat.chatwith', user=user))


##? SOCKET WORK BELOW ################################################################


@socketio.on('joined', namespace='/chatwith')
def joined(message):
    room = session.get('room')
    join_room(room)
    emit('status', {'msg': 'You entered the room.'}, room=room)


@socketio.on('text', namespace='/chatwith')
def text(message):
    key = "kisan123".encode()
    manager = DesKey(key)
    profileimg = f"/static/profilepics/{current_user.image_file}"
    receiver = session.get('receiver_id')
    room = session.get('room')
    the_msg = manager.encrypt(message["msg"].encode(), padding=True)
    user = User.query.filter_by(id=receiver).first_or_404()
    msg = Message(author=current_user, recipient=user,
                  message=the_msg)
    db.session.add(msg)
    user.unread_message_count()
    db.session.commit()
    emit('message', {
         'msg': message['msg'], 'userImg': profileimg}, room=room, include_self=False)


@socketio.on('left', namespace='/chatwith')
def left(message):
    room = session.get('room')
    leave_room(room)
    emit('status', room=room)

hamrokurakani/chat/templates/chat/chatter.html
{% extends "chat/nav.html" %}
{% block content %}

<div id="frame">
    <div id="sidepanel">
        <div id="profile">
            <img id="profile-img" src="{{ url_for('static', filename='profilepics/' + current_user.image_file) }}"
                class="d-none" />
            <p class="h5 font-weight-bold">Hamrokurani</p>
            <p class="text-muted small font-weight-bold"><span>
                    total messages: {{ getuser | countmessages }}
                </span></p>
        </div>

        <!--? CONTACT SECTION -->
        <div id="contacts">
            <ul>
                {% for user in users %}
                {% if user != current_user %}
                {% if user == getuser %}
                <li class="contact active">
                    {% else %}
                <li class="contact">
                    {% endif %}
                    <a class="noblue" href="{{ url_for('chat.chatwith', user=user.username) }}">
                        <div class="wrap">
                            {% if user != getuser and user.last_message_read_time | isactive == 'offline' %}
                            <span class="contact-status"></span>
                            {% elif user != getuser and user.last_message_read_time | isactive != 'offline' %}
                            <span class="contact-status online"></span>
                            {% else %}
                            {% endif %}
                            <img src="{{ url_for('static', filename='profilepics/' + user.image_file) }}" />

                            <div class="meta">
                                <p class="name">{{ user.fullname }}</p>
                                {% if user | lastmessageauthor == current_user %}
                                <p class="preview"><span>You: </span>{{ user | lastmessage | decrypt }}</p>
                                {% else %}
                                {% if not user | lastmessage %}
                                <p class="preview"><span>no conversations yet</span></p>
                                {% else %}
                                <p class="preview"><span>{{ user | lastmessage | decrypt }}</span></p>
                                {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    </a>
                </li>
                {% else %}
                {% endif %}
                {% endfor %}
            </ul>
        </div>

        <div id="bottom-bar">
            <button id="settings">
                <ul>
                    <li>
                        <a href="{{ url_for('users.settings') }}" class="noblue">
                            <i class="fa fa-cog fa-fw" aria-hidden="true"></i> <span>Settings</span></a>
                    </li>
                </ul>
            </button>
            <button id="exit">
                <ul>
                    <li class="disconnect"><a href="{{ url_for('chat.home') }}" class="noblue">
                            <i class="fa fa-sign-out" aria-hidden="true"></i><span>Exit</span></a></li>
                </ul>
            </button>
        </div>

    </div>

    <!-- ? MAIN MESSAGE SECTION -->
    <div class="content">
        <div class="contact-profile">
            <img src="{{ url_for('static', filename='profilepics/' + getuser.image_file) }}" />
            <p>{{getuser.fullname}}
                {% if getuser.last_message_read_time | isactive == 'offline' %}
                <small class="badge badge-pill badge-secondary"><b> {{ getuser.last_message_read_time | isactive }}
                    </b></small>
            </p>
            {% else %}
            <small class="badge badge-pill badge-success"><b> {{ getuser.last_message_read_time | isactive }}
                </b></small></p>
            {% endif %}
        </div>

        <div class="messages">
            <ul>
                {% for msg in messages %}
                {% set deletemessage = url_for('chat.deletemessage', id=msg.id, user=getuser.username) %}
                {% if msg.author == current_user %}
                <li class="replies">
                    {% else %}
                <li class="sent">
                    {% endif %}
                    <img src="{{ url_for('static', filename='profilepics/' + msg.author.image_file) }}" />
                    {% if msg.author == current_user %}
                    <p title="{{msg.timestamp | humanify }} ago">
                        {{ msg.message | decrypt }} · <a class="fixblue" href="{{ deletemessage }}">
                            <i class="fa fa-trash-o"></i></a></p>
                    {% else %}
                    <p title="{{msg.timestamp | humanify }} ago">{{ msg.message | decrypt }}</p>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
        </div>

        <div class="message-input">
            <div class="wrap">
                <input type="text" id="message" placeholder="Write your message..." />
                <button id="sendmessage"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
            </div>
        </div>

    </div>
</div>

{% endblock content %}

hamrokurakani/chat/templates/chat/nav.html
<!DOCTYPE html>
<html>

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/' + 'bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/' + 'better-nav.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/' + 'font-awesome.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/' + 'sourcesanspro.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename= 'css/' + 'chat.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename= 'css/' + 'main.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/' + 'reset.min.css') }}">
  </head>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('chat.home') }}">hamrokurakani</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          {% if current_user.is_authenticated %}

          <div class="navbar-nav mr-auto">
            {% if current_user.id == 1 %}
            <a class="nav-item nav-link text-white font-weight-bold text-uppercase"
              href="{{ url_for('admin.index') }}">Dashboard</a>
            {% endif %}
            <a class="nav-item nav-link text-white font-weight-bold text-uppercase"
              href="{{ url_for('users.logout') }}">Logout</a>
          </div>
          <div class="navbar-nav ml-auto">
            <p class="d-inline-block">
              <span class="current-user align-middle">
                <img src="{{ url_for('static', filename='profilepics/' + current_user.image_file) }}" />
              </span>
              <span class="text-white align-text-top font-weight-bold">
                @{{ current_user.username }}
              </span>
            </p>
          </div>
          {% else %}
          <a class="nav-item nav-link text-white font-weight-bold text-uppercase"
            href="{{ url_for('users.login') }}">Login</a>
          <a class="nav-item nav-link text-white font-weight-bold text-uppercase"
            href="{{ url_for('users.register') }}">Register</a>
          {% endif %}
        </div>
      </div>
      </div>
    </nav>
  </header>

  <body>
    {% block content %}
    {% endblock %}
  </body>

  <!-- JAVASCRIPT SECTION -->
  <script src="{{ url_for('static', filename='js/' + 'jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/' + 'socket.io.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/' + 'chat.js') }}"></script>
  <script src="{{ url_for('static', filename='js/' + 'popper.min.js') }}"></script>
  <script src="{{ url_for('static', filename= 'js/' + 'bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename= 'js/' + 'better-nav.min.js') }}"></script>

</html>

hamrokurakani/chat/templates/chat/users.html
{% extends "chat/nav.html" %}
{% block content %}

<div id="frame">
    <div id="sidepanel">
        <div id="profile">
            <p class="h5 font-weight-bold">Hamrokurani</p>
            <p class="text-muted small font-weight-bold"><span>
                    total users: {{total_users}}
                </span></p>
        </div>

        <div id="contacts">
            <ul>
                {% for user in users %}
                {% if user != current_user %}
                <li class="contact">
                    <a class="noblue" href="{{ url_for('chat.chatwith', user=user.username) }}">
                        <div class="wrap">
                            {% if user.last_message_read_time | isactive == 'offline' %}
                            <span class="contact-status"></span>
                            {% else %}
                            <span class="contact-status online"></span>
                            {% endif %}
                            <img src="{{ url_for('static', filename='profilepics/' + user.image_file) }}" />
                            <div class="meta">
                                <p class="name">{{ user.fullname }} </p>

                                <p class="preview">
                                    {% if user | newmessages > 0 %}
                                    <small class="badge badge-dark mb-1"><b> {{ user | newmessages }}
                                            Messages</b></small>
                                    {% else %}
                                    {% endif %}
                                    <span class="small font-weight-bold">last active {{ user.last_message_read_time |
                                        humanify }}
                                        ago</span>
                                </p>
                            </div>
                        </div>
                    </a>
                </li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>

        <div id="bottom-bar">
            <button id="settings">
                <ul>
                    <li>
                        <a href="{{ url_for('users.settings') }}" class="noblue">
                            <i class="fa fa-cog fa-fw" aria-hidden="true"></i> <span>Settings</span></a>
                    </li>
                </ul>
            </button>
            <button id="exit">
                <ul>
                    <li class="disconnect"><a href="{{ url_for('chat.home') }}" class="noblue">
                            <i class="fa fa-sign-out" aria-hidden="true"></i><span>Exit</span></a></li>
                </ul>
            </button>
        </div>

    </div>

    <div class="content">
        <div class="select-info">
            <p>Select a user from the sidepanel to start chatting!</p>
        </div>
    </div>

</div>
</div>

{% endblock content %}