bbcsocial/chat/routes.py
from flask import session, redirect, url_for, render_template, request, Blueprint
from flask_socketio import emit, join_room, leave_room
from flask_login import current_user, login_required
from bbcsocial import socketio, bcrypt, db
from bbcsocial.models import User, Message
from datetime import datetime
from bbcsocial.core.des import manager

chyat = Blueprint('chat', __name__)

@chyat.route('/')
@login_required
def home():
    users = User.query.all()
    return render_template('home.html', users=users)

@chyat.route('/chats')
@login_required
def chats():
    my_messages = Message.query.filter_by(recipient_id=current_user.id)
    messengers = [message.author.id for message in my_messages]
    senders = [User.query.get(sender) for sender in set(messengers)]
    return render_template('chat/users.html', senders=senders)


@chyat.route('/chatwith/<string:user>')
@login_required
def chatwith(user):
    getuser = User.query.filter_by(username=user).first_or_404()
    messages = []
    session['receiver_id'] = getuser.id
    session['room'] = int(getuser.id) * int(current_user.id)
    my_messages = Message.query.filter_by(recipient_id=current_user.id)
    messengers = [message.author.id for message in my_messages]
    senders = [User.query.get(sender) for sender in set(messengers)]
    msgs_received = list(Message.query.filter_by(
        recipient_id=current_user.id, sender_id=getuser.id).all())
    msgs_sent = list(Message.query.filter_by(
        recipient_id=getuser.id, sender_id=current_user.id).all())
    messages = msgs_received + msgs_sent
    messages.sort(key=lambda order_by: order_by.timestamp)
    current_user.last_message_read_time = datetime.now()
    # ? NEED TO USE AJAX HERE current_user.unread_message_count = msgs_received.count()
    for message in msgs_received:
        message.is_seen = True
    db.session.commit()
    return render_template('chat/chatter.html', getuser=getuser, senders=senders, messages=messages)


@chyat.route("/chatwith/<string:user>/deletemessage/<int:id>/")
@login_required
def deletemessage(user, id):
    message = Message.query.filter_by(id=id).first_or_404()
    if not current_user.is_authenticated and message.author != current_user:
        abort(403)
    db.session.delete(message)
    db.session.commit()
    return redirect(url_for('chat.chatwith', user=user))

##? SOCKET WORK BELOW ################################################################


@socketio.on('joined', namespace='/chatwith')
def joined(message):
    room = session.get('room')
    join_room(room)
    emit('status', {'msg': 'You entered the room.'}, room=room)


@socketio.on('text', namespace='/chatwith')
def text(message):
    profileimg = current_user.image_file
    receiver = session.get('receiver_id')
    room = session.get('room')
    user = User.query.filter_by(id=receiver).first_or_404()
    msg = Message(author=current_user, recipient=user, message=manager(message['msg'],"kisan123","encrypt"))
    db.session.add(msg)
    user.unread_message_count()
    db.session.commit()
    emit('message', {
         'msg':manager( message['msg'],"kisan123","decrypt"), 'profileimage': profileimg}, room=room, include_self=False)


@socketio.on('left', namespace='/chatwith')
def left(message):
    room = session.get('room')
    leave_room(room)
    emit('status', room=room)

bbcsocial/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from bbcsocial import db, bcrypt, login_manager
from bbcsocial.models import User
from bbcsocial.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from datetime import datetime

users = Blueprint('users', __name__)


@users.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.now()
        db.session.commit()


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('chat.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(fullname=form.fullname.data, username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your  account has been created! Happy Staying!!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('chat.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            db.session.commit()
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('chat.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('users.login'))

bbcsocial/templates/chat/chatter.html
{% extends "chat/nav.html" %}
{% block content %}

<script type="text/javascript"> var profile = "{{ current_user.image_file }}"; </script>

<div id="frame">
    <div id="sidepanel">
        <div id="profile">
            <div class="wrap">
                <img id="profile-img" src="{{ url_for('static', filename='profilepics/' + current_user.image_file) }}"
                    class="online" />
                <p>{{ current_user.fullname }} <span><small class="badge badge-secondary">
                            <b> {{ getuser | countmessages }} </b></small></span> </p>

            </div>
        </div>

        <div id="search">
            <label for=""><i class="fa fa-search" aria-hidden="true"></i></label>
            <input type="text" placeholder="Search contacts..." />
        </div>

        <!--? CONTACT SECTION -->
        <div id="contacts">
            <ul>
                {% for sender in senders %}
                {% if sender != current_user %}
                {% if sender == getuser %}
                <li class="contact active">
                    {% else %}
                <li class="contact">
                    {% endif %}
                    <a class="noblue" href="{{ url_for('chat.chatwith', user=sender.username) }}">
                        <div class="wrap">
                            {% if sender != getuser and sender.last_message_read_time | isactive == 'offline' %}
                            <span class="contact-status"></span>
                            {% elif sender != getuser and sender.last_message_read_time | isactive != 'offline' %}
                            <span class="contact-status online"></span>
                            {% else %}
                            {% endif %}
                            <img src="{{ url_for('static', filename='profilepics/' + sender.image_file) }}" />

                            <div class="meta">
                                <p class="name">{{ sender.fullname }}</p>
                                {% if sender | lastmessageauthor == current_user %}
                                <p class="preview"><span>You: </span> {{ sender | lastmessage }}</p>
                                {% else %}
                                <p class="preview"><span>{{ sender | lastmessage }} </span></p>
                                {% endif %}
                            </div>
                        </div>
                    </a>
                </li>
                {% else %}
                {% endif %}
                {% endfor %}
            </ul>
        </div>

        <div id="bottom-bar">
            <button id="addcontact">
                <ul>
                    <li>
                        <a href="#PeopleToMessage" data-toggle="modal" data-target="#PeopleToMessage" class="noblue">
                            <i class="fa fa-user-plus fa-fw" aria-hidden="true"></i> <span>Add Contact</span></a></li>
                </ul>
            </button>
            <button id="settings">
                <ul>
                    <li class="disconnect"><a href="{{ url_for('chat.home') }}" class="noblue">
                            <i class="fa fa-sign-out" aria-hidden="true"></i><span>Exit</span></a></li>
                </ul>
            </button>
        </div>

    </div>

    <!-- ? MAIN MESSAGE SECTION -->
    <div class="content">
        <div class="contact-profile">
            <img src="{{ url_for('static', filename='profilepics/' + getuser.image_file) }}" />
            <p>{{getuser.fullname}}
                {% if getuser.last_message_read_time | isactive == 'offline' %}
                <small class="badge badge-pill badge-secondary"><b> {{ getuser.last_message_read_time | isactive }}
                    </b></small></p>
            {% else %}
            <small class="badge badge-pill badge-success"><b> {{ getuser.last_message_read_time | isactive }}
                </b></small></p>
            {% endif %}
        </div>

        <div class="messages">
            <ul>
                {% for msg in messages %}
                {% set deletemessage = url_for('chat.deletemessage', id=msg.id, user=getuser.username) %}
                {% if msg.author == current_user %}
                <li class="replies">
                    {% else %}
                <li class="sent">
                    {% endif %}
                    <img src="{{ url_for('static', filename='profilepics/' + msg.author.image_file) }}" />
                    {% if msg.author == current_user %}
                    <p title="{{msg.timestamp | humanify }} ago">
                        {{ msg.message }} · <a class="fixblue" href="{{ deletemessage }}">
                            <i class="fa fa-trash-o"></i></a></p>
                    {% else %}
                    <p title="{{msg.timestamp | humanify }} ago">{{ msg.message }} </p>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
        </div>

        <div class="message-input">
            <div class="wrap">
                <input type="text" id="message" placeholder="Write your message..." />
                <button id="sendmessage"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
            </div>
        </div>

    </div>
</div>

<!--? LIST OF USERS IN BBCSOCIAL-->
<div id="PeopleToMessage" class="modal">
    <div class="modal-dialog modal-md pr-0 pl-0">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title">Send Message</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <!--?LIST OF USERS IN BBCSOCIAL STARTS HERE-->
            <div class="modal-body p-0 m-0">
                <ul class="list-unstyled">
                    {% for user in current_user.followed %}
                    <li class="media p-0 m-0">
                        <img class="rounded-circle post-img m-2"
                            src="{{ url_for('static', filename='profilepics/' + user.followed.image_file) }}">

                        <div class="media-body p-0 m-0">
                            <a href="{{ url_for('chat.chatwith', user=user.followed.username) }}"
                                class="btn-sm bold button mx-4 pl-4 pr-4 float-right no-underline active mt-1"
                                role="button">Message</a>

                            <small class="text-dark m-0 d-block mt-2"><b>{{ user.followed.fullname }}</b></small>
                            <small><a class="text-muted d-block"
                                    href="{{ url_for('users.user_posts', username=user.followed.username) }}">
                                    @{{ user.followed.username }}</a></small>
                        </div>
                    </li>
                    <hr class="nastyhr p-0 m-0 mb-1 mt-1 pl-0">
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

bbcsocial/templates/chat/nav.html
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/' + 'bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/' + 'better-nav.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/' + 'font-awesome.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/' + 'sourcesanspro.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename= 'css/' + 'chat.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename= 'css/' + 'main.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/' + 'reset.min.css') }}">
</head>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('chat.chats') }}">bbcsocial</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          {% if current_user.is_authenticated %}
          <div class="navbar-nav mr-auto">

            {% if current_user.id == 1 %}
            <a class="nav-item nav-link text-white font-weight-bold text-uppercase"
            href="{{ url_for('admin.index') }}">Dashboard</a>
             {% endif %}
             <a class="nav-item nav-link text-white font-weight-bold text-uppercase"
            href="{{ url_for('users.logout') }}">Logout</a>
          </div>
          {% else %}
          <a class="nav-item nav-link text-white font-weight-bold text-uppercase"
            href="{{ url_for('users.login') }}">Login</a>
          <a class="nav-item nav-link text-white font-weight-bold text-uppercase"
            href="{{ url_for('users.register') }}">Register</a>
          {% endif %}
        </div>
      </div>
      </div>
    </nav>
  </header>

<body>
    {% block content %}
    {% endblock %}
</body>

<!-- JAVASCRIPT SECTION -->
<script src="{{ url_for('static', filename='js/' + 'jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/' + 'app.js') }}"></script>
<script src="{{ url_for('static', filename='js/' + 'socket.io.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/' + 'chat.js') }}"></script>
<script src="{{ url_for('static', filename='js/' + 'popper.min.js') }}"></script>
<script src="{{ url_for('static', filename= 'js/' + 'bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename= 'js/' + 'better-nav.min.js') }}"></script>

</html>